### ISSUE TITLE
Failure in appearances crawler

### ISSUE THREAD

**Issue by dcaribou** [dcaribou/transfermarkt-scraper#81]
> ======================================================================
>ERROR: [appearances] parse_stats (callback)
> ----------------------------------------------------------------------
>Traceback (most recent call last):
>  File "/Users/david/transfermarkt-scraper/.venv/lib/python3.12/site-packages/scrapy/contracts/__init__.py", line 164, in cb_wrapper
>    output = cb(response, **cb_kwargs)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/david/transfermarkt-scraper/.venv/lib/python3.12/site-packages/scrapy/contracts/__init__.py", line 56, in wrapper
>    cb_result = cb(response, **cb_kwargs)
>                ^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/david/transfermarkt-scraper/.venv/lib/python3.12/site-packages/scrapy/contracts/__init__.py", line 59, in wrapper
>    output = list(iterate_spider_output(cb_result))
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>  File "/Users/david/transfermarkt-scraper/tfmkt/spiders/appearances.py", line 100, in parse_stats
>    assert(len(competitions) == len(stats_tables))
>AssertionError

**Comment by dcaribou** [comment]
It's likely the root cause of https://github.com/dcaribou/transfermarkt-datasets/issues/272
